# Generated by Django 5.0.6 on 2024-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('setor_abrev', models.CharField(db_collation='utf8mb3_general_ci', max_length=250)),
                ('orgao_full', models.CharField(db_collation='utf8mb3_general_ci', max_length=250)),
                ('setor_full', models.CharField(db_collation='utf8mb3_general_ci', max_length=250)),
                ('orgao_abrev', models.CharField(db_collation='utf8mb3_general_ci', max_length=250)),
            ],
            options={
                'db_table': 'setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomeusuario', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=1)),
                ('cpf', models.IntegerField(db_column='CPF')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
