# Generated by Django 5.0.6 on 2024-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacontabil',
            fields=[
                ('idcontacontabil', models.AutoField(primary_key=True, serialize=False)),
                ('tipocontacontabil', models.CharField(max_length=50)),
                ('durabilidade', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'contacontabil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depreciacao',
            fields=[
                ('iddepreciacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipodepreciacao', models.CharField(max_length=100)),
                ('datacomprafk', models.DateField(blank=True, null=True)),
                ('datamanutencaofk', models.DateField(blank=True, null=True)),
                ('valordepreciado', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'db_table': 'depreciacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idpatrimonio', models.AutoField(primary_key=True, serialize=False)),
                ('tombo', models.IntegerField()),
                ('marca', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('datacompra', models.DateField()),
                ('valorcompra', models.DecimalField(decimal_places=5, max_digits=20)),
                ('notafiscal', models.IntegerField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
    ]
