# Generated by Django 5.0.6 on 2024-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('idalocacao', models.AutoField(primary_key=True, serialize=False)),
                ('dataalocacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alocacao',
                'managed': False,
            },
        ),
    ]
