# Generated by Django 5.0.6 on 2024-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alocacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('idvisita', models.AutoField(primary_key=True, serialize=False)),
                ('datavisita', models.DateField(blank=True, null=True)),
                ('tombos_visita', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
    ]
