# Generated by Django 5.0.6 on 2024-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoestado', models.CharField(max_length=45)),
                ('descricaoestado', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
    ]
